# Generated by Django 5.1.1 on 2024-09-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories_reset',
            field=models.BooleanField(default=False),
        ),
    ]
