# Generated by Django 5.1.1 on 2024-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0002_meal_calories_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='foods',
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
