# Generated by Django 5.1.1 on 2024-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0003_remove_meal_foods_meal_calories_meal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
    ]
